apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: prometheus
# Cluster에대한 규칙 지정
rules:
########## 1
  - apiGroups: [""] # "" : cores 라는 그룹 ( 가장 기본적인 권한 )
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
# Do : get, list, watch
    verbs: ["get", "list", "watch"] # 권한을 부여할 수 있는 명령 get: 조회
########## 2
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"] # 리소스가 아닌 경로에 룰을 설정, /metrics 요청에는 get 권한만 허용
    verbs: ["get"]