
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
    app: {{ .Values.svc.backend }}
  type: {{ .Values.svc.type }}
  ports:
    - port: {{ .Values.svc.svcPort }}
      targetPort: {{ .Values.svc.targetPort }}
